pageinfo = [[1728780041,3079],
	[1728780767,2151],
	[1728778777,2060],
	[1728778675,2018],
	[1728778691,2032],
	[1728778735,2021],
	[1728780603,3137],
	[1728776009,1992],
	[1728778659,2032],
	[1728780163,2932],
	[1728778715,2030]];
pagedata = [ ["./bem_vindo.htm","Bem-Vindo","﻿Bem-Vindo Top Previous Next O SISCERT é um sistema inovador projetado para facilitar a geração e gestão de certificados em instituições de ensino...",""],
["./chapter_2.htm","Alunos","﻿Alunos Top Previous Next This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Software. All rights reserved. Th...",""],
["./configuracoes.htm","Configurar o Sistema","﻿Configurar o Sistema Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169;...",""],
["./cursos.htm","Cursos","﻿Cursos Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Software. ...",""],
["./disciplinas.htm","Disciplinas","﻿Disciplinas Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Softw...",""],
["./gerar_certificado.htm","Gerar Certificado","﻿Gerar Certificado Top Previous Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Soft...",""],
["./home.htm","Home","﻿Home Top Previous Next A tela inicial do SISCERT é projetada para ser intuitiva e de fácil navegação, permitindo que diferentes usuários, como co...",""],
["./introduction.htm","Introdução","﻿Introdução Top Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Software. All r...",""],
["./professores.htm","Professores","﻿Professores Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Softw...",""],
["./second_topic.htm","Público Alvo","﻿Público Alvo Top Previous Next Os usuários do SISCERT, que incluem o Coordenador da Pós-Graduação e o corpo administrativo, desempenham papéis cr...",""],
["./usuarios.htm","Usuários","﻿Usuários Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Software...",""]];
